import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layouts/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Providers from "@/components/provider/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SoundHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers>
        <div className="flex flex-col min-h-screen">
        <Navbar/>
        <main className="flex-1">{children}</main>
        <Footer/>
        </div>
        </Providers>
        </body>
    </html>
  );
}
