import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/provider/Provider";
import CustomerLayout from "@/components/layout/CustomerLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SoundHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <CustomerLayout>{children}</CustomerLayout>
        </Providers>
      </body>
    </html>
  );
}
